from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(427, 324)
        self.CircleBtn = QtWidgets.QRadioButton(parent=Dialog)
        self.CircleBtn.setEnabled(True)
        self.CircleBtn.setGeometry(QtCore.QRect(290, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CircleBtn.setFont(font)
        self.CircleBtn.setObjectName("CircleBtn")
        self.SquareBtn = QtWidgets.QRadioButton(parent=Dialog)
        self.SquareBtn.setEnabled(True)
        self.SquareBtn.setGeometry(QtCore.QRect(360, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SquareBtn.setFont(font)
        self.SquareBtn.setObjectName("SquareBtn")
        self.RectangleBtn = QtWidgets.QRadioButton(parent=Dialog)
        self.RectangleBtn.setEnabled(True)
        self.RectangleBtn.setGeometry(QtCore.QRect(290, 46, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RectangleBtn.setFont(font)
        self.RectangleBtn.setObjectName("RectangleBtn")
        self.TriangleBtn = QtWidgets.QRadioButton(parent=Dialog)
        self.TriangleBtn.setEnabled(True)
        self.TriangleBtn.setGeometry(QtCore.QRect(360, 46, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TriangleBtn.setFont(font)
        self.TriangleBtn.setObjectName("TriangleBtn")
        self.BaseSubmit = QtWidgets.QPushButton(parent=Dialog)
        self.BaseSubmit.setEnabled(True)
        self.BaseSubmit.setGeometry(QtCore.QRect(360, 150, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.BaseSubmit.setFont(font)
        self.BaseSubmit.setObjectName("BaseSubmit")
        self.Result = QtWidgets.QTextBrowser(parent=Dialog)
        self.Result.setGeometry(QtCore.QRect(10, 10, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Result.setFont(font)
        self.Result.setObjectName("Result")
        self.BaseLabel = QtWidgets.QLabel(parent=Dialog)
        self.BaseLabel.setEnabled(True)
        self.BaseLabel.setGeometry(QtCore.QRect(290, 100, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BaseLabel.setFont(font)
        self.BaseLabel.setObjectName("BaseLabel")
        self.HeightLabel = QtWidgets.QLabel(parent=Dialog)
        self.HeightLabel.setEnabled(True)
        self.HeightLabel.setGeometry(QtCore.QRect(290, 170, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HeightLabel.setFont(font)
        self.HeightLabel.setObjectName("HeightLabel")
        self.ClearBtn = QtWidgets.QPushButton(parent=Dialog)
        self.ClearBtn.setGeometry(QtCore.QRect(10, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ClearBtn.setFont(font)
        self.ClearBtn.setObjectName("ClearBtn")
        self.ModeBtn = QtWidgets.QPushButton(parent=Dialog)
        self.ModeBtn.setGeometry(QtCore.QRect(60, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ModeBtn.setFont(font)
        self.ModeBtn.setObjectName("ModeBtn")
        self.DelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.DelBtn.setGeometry(QtCore.QRect(110, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DelBtn.setFont(font)
        self.DelBtn.setObjectName("DelBtn")
        self.DivideBtn = QtWidgets.QPushButton(parent=Dialog)
        self.DivideBtn.setGeometry(QtCore.QRect(220, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DivideBtn.setFont(font)
        self.DivideBtn.setObjectName("DivideBtn")
        self.MultiplyBtn = QtWidgets.QPushButton(parent=Dialog)
        self.MultiplyBtn.setGeometry(QtCore.QRect(220, 150, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MultiplyBtn.setFont(font)
        self.MultiplyBtn.setObjectName("MultiplyBtn")
        self.SubtractBtn = QtWidgets.QPushButton(parent=Dialog)
        self.SubtractBtn.setGeometry(QtCore.QRect(220, 190, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SubtractBtn.setFont(font)
        self.SubtractBtn.setObjectName("SubtractBtn")
        self.AddBtn = QtWidgets.QPushButton(parent=Dialog)
        self.AddBtn.setGeometry(QtCore.QRect(220, 230, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.AddBtn.setFont(font)
        self.AddBtn.setObjectName("AddBtn")
        self.EqualsBtn = QtWidgets.QPushButton(parent=Dialog)
        self.EqualsBtn.setGeometry(QtCore.QRect(220, 270, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EqualsBtn.setFont(font)
        self.EqualsBtn.setObjectName("EqualsBtn")
        self.Btn7 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn7.setGeometry(QtCore.QRect(10, 150, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn7.setFont(font)
        self.Btn7.setObjectName("Btn7")
        self.Btn9 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn9.setGeometry(QtCore.QRect(150, 150, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn9.setFont(font)
        self.Btn9.setObjectName("Btn9")
        self.Btn8 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn8.setGeometry(QtCore.QRect(80, 150, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn8.setFont(font)
        self.Btn8.setObjectName("Btn8")
        self.Btn4 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn4.setGeometry(QtCore.QRect(10, 190, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn4.setFont(font)
        self.Btn4.setObjectName("Btn4")
        self.Btn5 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn5.setGeometry(QtCore.QRect(80, 190, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn5.setFont(font)
        self.Btn5.setObjectName("Btn5")
        self.Btn6 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn6.setGeometry(QtCore.QRect(150, 190, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn6.setFont(font)
        self.Btn6.setObjectName("Btn6")
        self.Btn1 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn1.setGeometry(QtCore.QRect(10, 230, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn1.setFont(font)
        self.Btn1.setObjectName("Btn1")
        self.Btn2 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn2.setGeometry(QtCore.QRect(80, 230, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn2.setFont(font)
        self.Btn2.setObjectName("Btn2")
        self.Btn3 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn3.setGeometry(QtCore.QRect(150, 230, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn3.setFont(font)
        self.Btn3.setObjectName("Btn3")
        self.Btn0 = QtWidgets.QPushButton(parent=Dialog)
        self.Btn0.setGeometry(QtCore.QRect(80, 270, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Btn0.setFont(font)
        self.Btn0.setObjectName("Btn0")
        self.DecimalBtn = QtWidgets.QPushButton(parent=Dialog)
        self.DecimalBtn.setGeometry(QtCore.QRect(150, 270, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DecimalBtn.setFont(font)
        self.DecimalBtn.setObjectName("DecimalBtn")
        self.PlusMinusBtn = QtWidgets.QPushButton(parent=Dialog)
        self.PlusMinusBtn.setGeometry(QtCore.QRect(160, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PlusMinusBtn.setFont(font)
        self.PlusMinusBtn.setObjectName("PlusMinusBtn")
        self.HeightSubmit = QtWidgets.QPushButton(parent=Dialog)
        self.HeightSubmit.setEnabled(True)
        self.HeightSubmit.setGeometry(QtCore.QRect(360, 220, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.HeightSubmit.setFont(font)
        self.HeightSubmit.setObjectName("HeightSubmit")
        self.BaseInput = QtWidgets.QLineEdit(parent=Dialog)
        self.BaseInput.setEnabled(True)
        self.BaseInput.setGeometry(QtCore.QRect(290, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BaseInput.setFont(font)
        self.BaseInput.setText("")
        self.BaseInput.setObjectName("BaseInput")
        self.HeightInput = QtWidgets.QLineEdit(parent=Dialog)
        self.HeightInput.setEnabled(True)
        self.HeightInput.setGeometry(QtCore.QRect(290, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HeightInput.setFont(font)
        self.HeightInput.setObjectName("HeightInput")
        self.ShapeSubmit = QtWidgets.QPushButton(parent=Dialog)
        self.ShapeSubmit.setEnabled(True)
        self.ShapeSubmit.setGeometry(QtCore.QRect(360, 70, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ShapeSubmit.setFont(font)
        self.ShapeSubmit.setObjectName("ShapeSubmit")
        self.LeftParBtn = QtWidgets.QPushButton(parent=Dialog)
        self.LeftParBtn.setGeometry(QtCore.QRect(10, 270, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LeftParBtn.setFont(font)
        self.LeftParBtn.setObjectName("LeftParBtn")
        self.RightParBtn = QtWidgets.QPushButton(parent=Dialog)
        self.RightParBtn.setGeometry(QtCore.QRect(40, 270, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RightParBtn.setFont(font)
        self.RightParBtn.setObjectName("RightParBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CircleBtn.setText(_translate("Dialog", "Circle"))
        self.SquareBtn.setText(_translate("Dialog", "Square"))
        self.RectangleBtn.setText(_translate("Dialog", "Rectangle"))
        self.TriangleBtn.setText(_translate("Dialog", "Triangle"))
        self.BaseSubmit.setText(_translate("Dialog", "Submit"))
        self.Result.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BaseLabel.setText(_translate("Dialog", "Base"))
        self.HeightLabel.setText(_translate("Dialog", "Height"))
        self.ClearBtn.setText(_translate("Dialog", "Clear"))
        self.ModeBtn.setText(_translate("Dialog", "Mode"))
        self.DelBtn.setText(_translate("Dialog", "Del"))
        self.DivideBtn.setText(_translate("Dialog", "/"))
        self.MultiplyBtn.setText(_translate("Dialog", "*"))
        self.SubtractBtn.setText(_translate("Dialog", "-"))
        self.AddBtn.setText(_translate("Dialog", "+"))
        self.EqualsBtn.setText(_translate("Dialog", "="))
        self.Btn7.setText(_translate("Dialog", "7"))
        self.Btn9.setText(_translate("Dialog", "9"))
        self.Btn8.setText(_translate("Dialog", "8"))
        self.Btn4.setText(_translate("Dialog", "4"))
        self.Btn5.setText(_translate("Dialog", "5"))
        self.Btn6.setText(_translate("Dialog", "6"))
        self.Btn1.setText(_translate("Dialog", "1"))
        self.Btn2.setText(_translate("Dialog", "2"))
        self.Btn3.setText(_translate("Dialog", "3"))
        self.Btn0.setText(_translate("Dialog", "0"))
        self.DecimalBtn.setText(_translate("Dialog", "."))
        self.PlusMinusBtn.setText(_translate("Dialog", "+/-"))
        self.HeightSubmit.setText(_translate("Dialog", "Submit"))
        self.ShapeSubmit.setText(_translate("Dialog", "Submit"))
        self.LeftParBtn.setText(_translate("Dialog", "("))
        self.RightParBtn.setText(_translate("Dialog", ")"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())